### ISSUE TITLE
Add Ability to modify vanilla mobs

### ISSUE THREAD

**Issue by AAli107** [Team-MCToolkit/MCToolkit#103]
A way to change vanilla mobs properties, it doesn't need to rewrite the entire mob's code. it only modifies a value or something related to that mob, like the health, the drops, Breed Item, etc.

**Comment by NatePlays95** [comment]
Writing the whole mob again might be easier, as most Minecraft classes use tons of private fields (meaning you can't modify them from outside), but even that is not simple

**Comment by Max094Reikeb** [comment]
Please respect the "new feature" template
