### ISSUE TITLE
Removing/Disabling Vanilla Advancements

### ISSUE THREAD

**Issue by Trolmaso** [Team-MCToolkit/MCToolkit#104]
**Describe the feature**

This feature would allow someone to remove or disable vanilla advancements. By this, I mean that they won't show up in the advancement menu and that they won't appear (in chat, menu, or top-right) when the player meets the criteria for the advancement. This feature would remove _all_ vanilla advancements

**How would you implement it?**

This could be a procedure, an option in the advancement creator, or in the workspace settings area, but I'm not really sure where it would be added.

**Additional Content**

This is currently possible by overwriting the vanilla advancement roots with advancements with impossible criteria/trigger.
But it is tedious because you have to put each file one by one into the Project File Browser because you can't directly copy-paste the files into it, so it will be nice if we had a simple toggle.

**Comment by titedog** [comment]
I don't think it would be wise to have the ability to disable vanilla advancements because you could screw stuff up and it may cause compatibility errors in mods that override advancements

**Comment by Goldorion** [comment]
It's not possible to remove a default advancement.
