### ISSUE TITLE
Timer procedure block

### ISSUE THREAD

**Issue by supermj767** [Team-MCToolkit/MCToolkit#107]
i love the idea of MCToolkit and would like to suggest a feature to add that MCreator does not have, if it's possible.

a procedure block that waits a number of ticks/seconds or more

"Wait __  (ticks/seconds/minutes/hours)"

basically just wait a number of ticks.
i know this is possible with variables, but variables can be complicated, it would be much better if this procedure block did exist to simplify it.

**Comment by titedog** [comment]
This is literally already implemented into MCToolkit

**Comment by titedog** [comment]
You also didn't even follow the format for Feature Requests so this will likely be taken down by a mod

**Comment by Max094Reikeb** [comment]
Indeed, no need for a feature idea that is being added... And you did not respect the format for feature requests.

**Comment by supermj767** [comment]
im sorry, i didn't know this was already a thing. i also didn't know there was a format for feature requests, can you delete this issue?

**Comment by titedog** [comment]
This request has already been closed. You should've known about the format because if you open a feature request it literally automatically puts the format into the box where you write your feature request.
