### ISSUE TITLE
Tags in repair items etc

### ISSUE THREAD

**Issue by makcccc** [Team-MCToolkit/MCToolkit#112]
**Describe the feature**

Ability to use tags in repair items in tools generator(if possible. i dont know is it possible or not but hope so)

**How would you implement it?**

add ability to use tags in repair items like recipes do

**Additional context**

i really want this so please :c

**Comment by Max094Reikeb** [comment]
I'm working on it. It's not possible to add tags in lists (for repair items in tool mod element) but I can add tags to the item based for tool pack and armor pack.

**Comment by Max094Reikeb** [comment]
After a check, using tags for tool pack and armor pack base item isn't possible. The base item is linked to the repair item, which can't be a tag. Therefore, I'm closing this issue.
