### ISSUE TITLE
New discord channel for teaming

### ISSUE THREAD

**Issue by scorpion981** [Team-MCToolkit/MCToolkit#115]
**Describe the feature**

A new channel made to recruit and join teams of other modders

**How would you implement it?**

In the others section in the discord.

**Additional context**

Maybe a bot can be useful to manage that.

**Comment by Max094Reikeb** [comment]
Uh? GitHub is for things about the software. If you want to make suggestions about the Discord, well make them on Discord lol. Anyways, closing this...
