### ISSUE TITLE
Updating the [Random(0,1)] procedure block

### ISSUE THREAD

**Issue by TheDerpySupport** [Team-MCToolkit/MCToolkit#116]
**Describe the feature**

I would simply like for the team to update the block to allow us to manually set what the random numbers are for the procedure block. So instead of being stuck with [0,1] we could change it to like [10,48] if we wanted to. It would help narrow and make concise randomized numbers instead of being stuck with a 1, 10, 1000, etc "percentage" such as 0.01/1.

**How would you implement it?**

Existing procedure block, just allow us to change the content within the block.

**Additional context**

N/A

**Comment by titedog** [comment]
cool suggestion except i already suggested this xD

**Comment by Max094Reikeb** [comment]
Indeed, a rewrite of the RNG procedures has been already requested in #72
