### ISSUE TITLE
Revamped Enchantment Mod Element

### ISSUE THREAD

**Issue by MrCreeps** [Team-MCToolkit/MCToolkit#118]
**Describe the feature**

Currently enchantments are kind of complex to new modders. I think a triggers page should be added to the enchantment mod element.

**How would you implement it?**

Instead of having to do a player-tick-update procedure and test for the item in the main hand of the player, there should be a "if enchantment applied to item" and "if enchanted gear worn" (From there add the entity damaged procedure if it is a thorns enchantment).

**Additional context**

This idea would make making a lot of enchantments easier for new modders.

**Comment by titedog** [comment]
I disagree. I think they should stay how they are only because enchants work completely fine on there own. If you make everything more simple for modders then they are never going to learn how to fully use the extent of MCreator.

**Comment by Max094Reikeb** [comment]
@titedog has a point.

**Comment by MrCreeps** [comment]
Yeah, I understand
