### ISSUE TITLE
New Procedure Value: Entity Velocity

### ISSUE THREAD

**Issue by titedog** [Team-MCToolkit/MCToolkit#130]
**Describe the feature**

A new procedure number value that would be able to get the velocity of an entity.

**How would you implement it?**

This would be located in "Entity Data" in the procedure editor, and would have an input for the target entity (default input would be "Event/Target Entity") which would get the current velocity of the entity as a vector. It would return as [0, 0, 0] if the entity was not moving, and if it is moving it would return as the velocity represented as a vector. If possible, I think it would be easier to return as a value like 0.0 or something, but I don't know if this is possible because my only knowledge on getting entity motion is through a vector.

**Comment by Max094Reikeb** [comment]
X, Y and Z entity velocity procedure blocks are already available.
<img width="263" alt="Capture d’écran 2020-12-02 à 10 08 42" src="https://user-images.githubusercontent.com/49318596/100852202-7352cb80-3486-11eb-95a2-a6125c41b540.png">
