### ISSUE TITLE
Download for MCtoolkit not working

### ISSUE THREAD

**Issue by YBOUZL** [Team-MCToolkit/MCToolkit#139]
**Describe the Bug**

I cannot download the software or make a post to software support

**Steps To Reproduce**

I have a Mac Mini, and I cant download
NOTE: this may be me just missing the download button, but I cant seem to download it.

**Screenshots**

no screenshots

**Details**
 - MCToolkit/MCreator version: 202X.X
 - Generator type: website?
 - OS: IOS
**Minimal reproducible example workspace**

If the bug is related to the workspace, *always* provide a minimal reproducible example 
workspace, export it to a shareable ZIP file, and attach it to the ticket.

Keep in mind your workspace of the project is not minimal reproducible example.
Make a workspace only with elements crucial for the bug.

**Logs**

If applicable, include game or build logs (full logs, do not crop them, in text format, 
screenshots of logs are not acceptable) from the Console tab or terminal and steps to reproduce the bug in your workspace. 

Longer logs should be posted on a paste service and linked here.

**Additional context**

**Comment by ShockingArtist** [comment]
Seriously?

**Comment by ShockingArtist** [comment]
The software is not ready for download yet...

**Comment by Max094Reikeb** [comment]
There is no download lol
