### ISSUE TITLE
Not a bug for MCToolkit, but it's website

### ISSUE THREAD

**Issue by thepwrtank18** [Team-MCToolkit/MCToolkit#140]
**Describe the bug**

When you go on the website (http://www.mctoolkit.net), the font is broken and the downloads (http://www.mctoolkit.net/download) are broken.

**Steps To Reproduce**

1. Go to http://mctoolkit.net/download.
2. Notice that the fonts are broken.
3. Notice that you can't download it.

**Screenshots**

**Details**
 - OS: Windows
 - Browser: Brave (Tested on Chrome too, same issue)

**Comment by thepwrtank18** [comment]
It's also warning me that the site is "Not Secure".

**Comment by titedog** [comment]
Somebody already made the same issue today. You cannot download the software it is not even close to ready. The website is still being worked on by the devs so please look more carefully before posting issues that have already been answered or are blatantly obvious.
