### ISSUE TITLE
Potion Item, Lingering Potion - Effect Arrow name bug

### ISSUE THREAD

**Issue by Blackout03** [Team-MCToolkit/MCToolkit#149]
**Describe the bug**

Lingering Potion and Potion Effect Arrow have their names swapped

**Steps To Reproduce**

Open latest MCToolkit on this Github,
Create a potion item and place the effects you want
Check the item names in-game

When possible, attach your MCToolkit/MCreator workspace (preferably a minimal example workspace required to reproduce the bug; use File -> Export workspace to a shareable ZIP...).

https://www.dropbox.com/s/y93po5ynjumeakf/broken.zip?dl=0

Please specify which mod elements to check in your workspace too, if applicable.

XGJHFGJ

**Screenshots**

![image](https://user-images.githubusercontent.com/45116222/101271138-60b4fb00-37d4-11eb-9e4a-8fd365d91286.png)
![image](https://user-images.githubusercontent.com/45116222/101271212-de790680-37d4-11eb-8151-06a7d7a1d643.png)
![image](https://user-images.githubusercontent.com/45116222/101271220-ec2e8c00-37d4-11eb-897d-5b00a96bbfa0.png)

**Details**
 - MCToolkit/MCreator version: 2020.6
 - Generator type: forge-1.15.2
 - OS: Windows

**Minimal reproducible example workspace**

If the bug is related to the workspace, *always* provide a minimal reproducible example 
workspace, export it to a shareable ZIP file and attach it to the ticket.

Keep in mind your workspace of the project is not a minimal reproducible example.
Make a workspace only with elements crucial for the bug.

**Logs**

If applicable, include a game or build logs (full logs, do not crop them, in text format, 
screenshots of logs are not acceptable) from the Console tab or terminal and steps to reproduce the bug in your workspace. 

Longer logs should be posted on a paste service and linked here.

**Additional context**

**Comment by Goldorion** [comment]
Oopsi
