### ISSUE TITLE
When night fall global trigger

### ISSUE THREAD

**Issue by scorpion981** [Team-MCToolkit/MCToolkit#15]
**Describe the feature**

A global trigger that activate when night fall

**How would you implement it?**

In the global trigger section in procedure

**Additional context**

Maybe add one for when the day come.

**Comment by LucyNoel** [comment]
I think that would be cool!! and really Useful!!

**Comment by Max094Reikeb** [comment]
There isn't any event to make this trigger. A solution could be to check every tick (with the `on world tick update` trigger) if it's night.
