### ISSUE TITLE
MacOS Exports

### ISSUE THREAD

**Issue by ApposModding** [Team-MCToolkit/MCToolkit#157]
When using Idea to run the command ./gradlew exportMac64, the .app file does not work
it just says 'appname' cannot be launched

-------------------------INFO----------------------
MacOS Version: 10.14.6
JDK Version: 1.8.0_61
Java Version: 1.8.0_271

**Comment by Goldorion** [comment]
You can not export MCToolkit on Mac.

**Comment by Max094Reikeb** [comment]
Gradle export hasn't been coded to work on Mac.

**Comment by ApposModding** [comment]
then code it!

**Comment by Max094Reikeb** [comment]
> then code it!

Uh I don't know how LOL
