### ISSUE TITLE
Full free editing of the assets

### ISSUE THREAD

**Issue by EpicNecromancer** [Team-MCToolkit/MCToolkit#173]
**Description**
Okay, this is kind of a long shot for a request, but it would be nice.
I'd think it would be great if full editing of the assets (textures, models, blockstates, sounds and sounds.json, etc.) could be done without locking the code. There's a lot that's possible with just those (such as adding custom subfolders making navigation easier or having multiple random variations of one block), but in MCreator at least, you can't do any of it without locking code.
Also, custom texture paths for entities would be nice. I know you're adding an "entity" folder for textures, but if you look at the Vanilla assets, many mobs have custom subfolders. It's pretty easy to change the texture path of entities in the code, so a way to do this would be great.

**Implementation**

Simply, editing anything in the assets wouldn't lock the code. Additionally, you're able to set a _path_ for entity textures, as opposed to just `textures/entity` and nothing more.
If the first thing isn't gonna work, you could have it so individual parts of the block's code (such as just the model(s) or blockstate) gets locked without the main Java.

Thanks for reading, and I hope you consider it! As someone who does a lot of resource packs and JSON (trying to learn Java but not there yet), I'm often frustrated by the limit of things that can be done to the assets easily in MCreator. A lot can be done with assets (for example, custom sound subfolders so that anyone who cracks open your sounds folder doesn't go insane), but not without locking code.

**Comment by Goldorion** [comment]
I already added the possibility to add/put textures in subdirectories. Read our changelog on our website https://mctoolkit.net/changelog/

**Comment by Max094Reikeb** [comment]
> [...] could be done without locking the code

Unfortunately, it's impossible. For example, if you link a procedure to a block, the import of the procedure is automatically added to your block, while if your code is locked, it's impossible to do that. Globally, you can't regenerate an element's code if the code is locked.
