### ISSUE TITLE
Better Living Entity Element 

### ISSUE THREAD

**Issue by PlummetStudios** [Team-MCToolkit/MCToolkit#181]
This feature is actually a few smaller features that would massively improve the current living entity mod element. 

First, an option for custom variants to make different versions of the same mob Male/Female/Child) 

Second, a new trigger for OnFed for when the player feeds a specific item to the entity.

Third, separating breeding from AI so that it doesn’t overwrite everything 

finally, more unique AI bases such as vexes, fox, dolphins, and fish. 

These would all be featured in the living entity mod element.

**Comment by Max094Reikeb** [comment]
> Third, separating breeding from AI so that it doesn’t overwrite everything

Why would you do that? Breeding doesn't overwrite the AI. It should stay as it is.

**Comment by Goldorion** [comment]
Please suggest one feature by issue.
