### ISSUE TITLE
Impossible to create a new Forge workspace

### ISSUE THREAD

**Issue by Max094Reikeb** [Team-MCToolkit/MCToolkit#183]
**Describe the bug**

I tried to create a new Forge workspace but it doesn't work. The workspace is created but every dependency isn't downloaded.

**Steps To Reproduce**

Just open the current GitHub version of MCToolkit and create a new Forge workspace.

**Details**
 - MCToolkit version: current GitHub
 - Generator type: forge-1.15.2 & forge-1.16.4
 - OS: MacOS
 
 **Links**
 Video: [https://vimeo.com/493935812](https://vimeo.com/493935812)

**Comment by Goldorion** [comment]
Can you see the JAR file of Forge in External libraries?

**Comment by Max094Reikeb** [comment]
> Can you see the JAR file of Forge in External libraries?

No. I edited the main message so you have a video of what happens.
