### ISSUE TITLE
"Can Player respawn here" option does not work

### ISSUE THREAD

**Issue by Uraneptus333** [Team-MCToolkit/MCToolkit#192]
**Describe the bug**

Even if the option "can player respawn here" in the dimension mod element is ticked, the player can't respawn in the dimension

**Steps To Reproduce**

[https://www.mediafire.com/file/baftbov3xg5fpgv/Dim_test.zip/file]()
Dimension mod element called "Test"

**Screenshots**
Video: [https://streamable.com/60uk5c](url)

**Details**
 -MCreator version: EAP 2020.6.52319
 - Generator type: forge-1.16.4
 - Windows

**Logs**
Console: [https://pastebin.com/0HjjLqjT](url)
Debug log: [https://pastebin.com/T884965m](url)
Latest log: [https://pastebin.com/MQi9SnyY](url)

**Comment by NOYBss** [comment]
Since MCreator didn't ended yet, could you open a issue in MCreator's GitHub, so it can be fixed in the next snapshot/release.

**Comment by Max094Reikeb** [comment]
Indeed. I'm closing this issue and you should reopen it on MCreator's GitHub.
