### ISSUE TITLE
Redstone Procedure blocks

### ISSUE THREAD

**Issue by SantinoIannuzzi** [Team-MCToolkit/MCToolkit#196]
I think that it would be usefull to be able to control Redstone signals from Procedures. And would need only three new blocks.

Get Redstone power on X Y Z

Emit Redstone signal on X Y Z power:

Emit Redstone signal on X Y Z from side: power:

**Comment by Max094Reikeb** [comment]
You already have those:
```
Get the indirect power of block at x: %1 y: %2 z: %3
Get redstone power on side %4 of block at x: %1 y: %2 z: %3
```

**Comment by Max094Reikeb** [comment]
But to emit a redstone signal on X Y Z, I'm not sure if it's possible...

**Comment by SantinoIannuzzi** [comment]
You already can emit redstone with the redstone condition that You had made. But with "Emit a redstone signal on X Y Z power:" You could emit Redstone in other place, not only in the exact block. Also with "Emit a Redstone signal on X Y Z from side: power:" You can make components like comparators.

**Comment by NOYBss** [comment]
Well, if there was a thing to set it, it would conflict with the amount of redstone power block is returning, block would return another value and you would try to set it to another value, and they would simply conflict with each other.
Anyways, there is just a getter.

**Comment by SantinoIannuzzi** [comment]
But if this offers more possibilities, wouldn't it be better to have the Procedure blocks instead of the condition?

**Comment by Max094Reikeb** [comment]
> But if this offers more possibilities, wouldn't it be better to have the Procedure blocks instead of the condition?

No. Conditions don't work (I made a PR but after testing in-game it doesn't work) and using procedure blocks to emit a redstone power at x y z isn't possible it seems.

**Comment by SantinoIannuzzi** [comment]
In that case, I think we can say goodbye to Redstone mods made with MCToolkit.

**Comment by Max094Reikeb** [comment]
There are already 3 procedure blocks in MCreator/MCToolkit, and I added Block property to emit redstone, along with an upcoming PR.
<img width="561" alt="Capture d’écran 2021-01-02 à 17 35 34" src="https://user-images.githubusercontent.com/49318596/103461767-1cf4d900-4d21-11eb-85d2-a60167bb317a.png">
