### ISSUE TITLE
Folder for mod elements

### ISSUE THREAD

**Issue by willpill** [Team-MCToolkit/MCToolkit#207]
**Describe the feature**

Folder for mod elements to organize a bit better

**How would you implement it?**

A folder, just like an element it takes up one space, and when clicked, it expands, probably would be suitable for the UI&UX update

**Additional context**

There are already topics for this and Klemen already said this will be added eventually, but since the development of MCreator is slowing (and might stop any time) & I cannot find anything related to this in either of the repository issues I will put it here

**Comment by Goldorion** [comment]
Just learnt to search, please. https://github.com/Team-MCToolkit/MCToolkit/issues/114

**Comment by willpill** [comment]
Oh sorry i did not see it
