### ISSUE TITLE
Unable to import textures

### ISSUE THREAD

**Issue by Max094Reikeb** [Team-MCToolkit/MCToolkit#212]
**Describe the bug**

When I want to import a texture, it doesn't. It creates the folder `textures` and then, import the texture with a modified name. For example, if I want to import block texture named `cauldron`, it places the texture just inside `textures` folder (instead of `textures/blocks` and renames `cauldron` into `blocks/cauldron`

**Steps To Reproduce**

1. In the resource tab, click on "Import textures"
2. Select "Import block texture(s)
3. Select your texture (mine was in `Download` folder)
4. Go inside your `src/main/resources/assets/mod_id/textures` folder and check out.

**Screenshots**

<img width="540" alt="Capture d’écran 2021-01-03 à 12 22 27" src="https://user-images.githubusercontent.com/49318596/103477348-5fb8be80-4dbe-11eb-881e-d078630b6873.png">

**Details**
 - MCToolkit version: current GitHub one
 - Generator type: forge-1.16.4
 - OS: MacOS

**Comment by Goldorion** [comment]
I just tested it, and it works correctly for me.

**Comment by Max094Reikeb** [comment]
You're not on MacOS

**Comment by Goldorion** [comment]
> 
> 
> You're not on MacOS

So I won't be able to fix myself as I can't test. You will have to fix it.

**Comment by Max094Reikeb** [comment]
> > You're not on MacOS
> 
> So I won't be able to fix myself as I can't test. You will have to fix it.

You already fixed bugs that were only on MacOS before...

**Comment by Goldorion** [comment]
I'm not sure what's the cause of the problem, but I will continue to search on the code. I will let you know if I find something.

**Comment by Goldorion** [comment]
I think I found the cause (same cause as #150). Can you try with this branch, please? https://github.com/Goldorion/MCToolkit/tree/bug-212

**Comment by Max094Reikeb** [comment]
Yes, what you did works. You can make a PR now.
