### ISSUE TITLE
Ability to Change Textures of Items/Blocks with overlays and or procedures.

### ISSUE THREAD

**Issue by Kunyee** [Team-MCToolkit/MCToolkit#219]
As the title suggests. The ability to change the texture of items and or blocks within a procedure or an overlay would be great.

Either as a procedure like change texture of (provided itemstack) to (select texture)

or

add overlays that we can add to items through the procedure like add texture overlay of (provided itemstack) to (select the overlay)

I'm working on a mod that has an Item upgrade system, and I feel this would be a good feature for many other users of programs like this. It could also allow for some really cool customization features.

**Comment by Max094Reikeb** [comment]
Please respect the Feature request template. This feature was already requested, so please, read all existing issues before making a new one. [MCToolkit#34](https://github.com/Team-MCToolkit/MCToolkit/issues/34)
