### ISSUE TITLE
Textures bug - MacOS

### ISSUE THREAD

**Issue by Max094Reikeb** [Team-MCToolkit/MCToolkit#22]
**Describe the bug**

This bug messes with texture paths when we use a texture for a block, an item, ...

**Steps To Reproduce**

1. Create a texture (or import one) and then create a block or an item or whatever uses a texture.
2. Make your mod element with this texture (and save it)
3. Done! Launch your game, you'll see no texture. The preview of the mod element will be blank (the preview is generated from the texture) and if you open the `.json` file of your mod element, you'll see something like this : 
`"layer0": "developmentworkspace:items//Users/*******/MCreatorWorkspaces/developmentworkspace/src/main/resources/assets/developmentworkspace/textures/items/sizied/sizied.png"`

**Details**
 - MCToolkit version : the one from this GitHub
 - Generator type: forge-1.15.2
 - OS: MacOS

**Other links**
Here's the video link : [https://vimeo.com/476305959](https://vimeo.com/476305959)

**Comment by Goldorion** [comment]
I just tried to reproduce the bug, but I wasn't able. It works perfectly for me with a texture in the default folder and with a texture in a custom subdirectory. Can you give me more details, please?

**Comment by Max094Reikeb** [comment]
I can try to come up with a video to show you exactly how I did so...

**Comment by Max094Reikeb** [comment]
Here's the video link to show you : [https://vimeo.com/476305959](https://vimeo.com/476305959)

**Comment by Blackout03** [comment]
Maybe it has to do with when saving the texture it says armour instead of item or block for the sub folder name

**Comment by Max094Reikeb** [comment]
No, if you watch the video, you'll see I have a first field to say the item name and then the armor folder name (which doesn't make any sense)

**Comment by Blackout03** [comment]
that is exactly what I said xD that the folder name says armour so maybe that is the error or something

**Comment by Goldorion** [comment]
I just re-tested, and it still works perfectly fine for me. I don't know what is your problem. However, I can still fix the wrong text.

**Comment by Max094Reikeb** [comment]
The bug is still there. It only appears on MacOS. @CrispyChips6660 can testify.

**Comment by ShockingArtist** [comment]
macOS big sur, perfectly fine for me

**Comment by Max094Reikeb** [comment]
> macOS big sur, worked perfectly fine for me, was not able to reproduce this issue

Could you record your screen while you're doing the steps please?

**Comment by ShockingArtist** [comment]
@Max094Reikeb 
https://vimeo.com/user116615367/review/484908809/1a2d05b462

**Comment by ShockingArtist** [comment]
Also, would you mind if you also show the part when you run the game with the item's blank texture?

**Comment by Max094Reikeb** [comment]
@ShockingArtist we are in MCToolkit GitHub, why did you do your video with MCreator and not MCToolkit?

**Comment by ShockingArtist** [comment]
wait. I thought you used MCreator as well as the menu says MCreator not MCtoolkit

**Comment by Max094Reikeb** [comment]
Read the details I provided :
- MCToolkit version : the one from this GitHub
- Generator type: forge-1.15.2
- OS: MacOS

**Comment by Max094Reikeb** [comment]
> Also, would you mind if you also show the part when you run the game with the item's blank texture?

Oh, and when I run the game, the items have the default texture when there isn't one (square with purple and black)

**Comment by ShockingArtist** [comment]
You are absolutely correct, The bug is there, my fault
