### ISSUE TITLE
Blocks made with Building Pack are ghost blocks

### ISSUE THREAD

**Issue by TeamRIS** [Team-MCToolkit/MCToolkit#222]
How To reproduce: 
1. make a texture
2.make a pack using the building pack
3. Run Minecraft and place the block
4. You can Walk through the block

(this does not happen with manually created blocks

 - MCToolkit/MCreator version: 2021.2
 - Generator type: forge-1.16.4
 - OS: Windows 10

**Comment by Max094Reikeb** [comment]
1. Could you give your workspace?
2. Are you using MCreator or MCToolkit? You did not delete the unused one.
> MCToolkit/MCreator version: 2021.2

3. Did you check if this bug happens on MCreator if you're using MCToolkit?

**Comment by Goldorion** [comment]
> 1. Could you give your workspace?
> 2. Are you using MCreator or MCToolkit? You did not delete the unused one.
> 
> > MCToolkit/MCreator version: 2021.2
> 
> 1. Did you check if this bug happens on MCreator if you're using MCToolkit?

**Building pack**, so it’s with MCToolkit only.

**Comment by TeamRIS** [comment]
I deleted the bugged blocks, But reproduce the error by following the steps given

**Comment by Max094Reikeb** [comment]
> I deleted the bugged blocks, But reproduce the error by following the steps given

Still, you need to provide an example workspace.
