### ISSUE TITLE
Can't download the binary

### ISSUE THREAD

**Issue by russinet** [Team-MCToolkit/MCToolkit#224]
**Describe the bug**

There are literally no buttons on the website to download the MCToolkit and I couldn't find anything in the source either

**Steps To Reproduce**

Just go to the MCToolkit download page

**Comment by Shadowdragon019** [comment]
MCToolkit isn't released for download yet

**Comment by russinet** [comment]
> MCToolkit isn't released for download yet

Well, where can I find binaries or builds?

**Comment by Shadowdragon019** [comment]
I think so. You'll have to compile MCToolkit yourself if I'm correct.

**Comment by Goldorion** [comment]
There are **NO** snapshots, stable versions or other builds released. Please search a bit on our website, our Discord server or this repository.
