### ISSUE TITLE
Element of the workspace disapearing

### ISSUE THREAD

**Issue by scorpion981** [Team-MCToolkit/MCToolkit#229]
**Describe the bug**
This morning I just came back to my workspace and I was surprised that the armor I created last time wasn't there anymore, at least, in the mcreator workspace. Because I recreated the armor and runned the game and there was 2 armors but the previous one I made last time had a weird name (look at the screenshot)

**Screenshots**

[https://media.discordapp.net/attachments/758827019621892126/803977923291774996/unknown.png](url)

**Details**
 - MCToolkit version: [e.g. 2021.1]
 - Generator type: [e.g. forge-1.15.2]
 - OS: [e.g. Windows]
](https://media.discordapp.net/attachments/758827019621892126/803978969618579466/unknown.png)

**Minimal reproducible example workspace**

To make sure the bug is happening I added my full workspace because with all the other elements it did not happen even if it was an armor.
](https://www.mediafire.com/file/9a8bolpq86eflzr/Backup+0.zip/file)
It happen to the tiger clothes

**Additional context**

I used a Java model for the head of the armor (and he was working really weird, not following the head completly when it turn) ¯\_(ツ)_/¯

**Comment by Max094Reikeb** [comment]
This GitHub is not the GitHub of MCreator. Please do not report MCreator bugs here. Report your bug on MCreator GitHub.

**Comment by scorpion981** [comment]
oops
