### ISSUE TITLE
All The Features I Want

### ISSUE THREAD

**Issue by ApposModding** [Team-MCToolkit/MCToolkit#230]
Entity-
Entity Bases- Villager, Warden(for 1.17+) and Piglin
Spawn Egg Customization- Select Texture, Model
Block-
None
Item-
None
GUI- 
Fullscreen GUI
Progress Bars Linked to Varible
Button Textures
Vanilla Crafting Table GUI Template
APIs-
Obfuscate- 1.14.4, 1.15.2 and 1.16.4
Patchwork- 1.14.4 FML and 1.16.4 FML
OpenCubicChunks- 1.12.2, 1.14.4, 1.15.2, 1.16.4/5, 1.17-Snapshot
VanillaFix- 1.12.2
Not Enough Crashes- 1.15.2, 1.16.1,2,3,4,5
Capes- FML and Fabric
Flies- 1.12.2, 1.14.4, 1.15.2, 1.16.4 FML 1.15.2, 1.16.4 Fabric

Mod elments- 
Patchuli Book
Animated Block
Remove
3-D Model Creator

Procedures-
Change player model
Set entity Atribute- Jump Power, Fall Speed, Player Health
Show Advanced blocks in Search

Triggers- 
Call 2 Procedures on single event

Packs
Glass Pack
Color Pack
Stone Pack

Generators

Full Fabric Support- 1.14.4, 1.15.2, 1.16.4/5 1.17-Snapshot
Rift- 1.13x
Cape Model
MCPE Recorce Pack

Biomes-
Custom Caves

Dimensions- 
Custom Sky

Overlays-
Fullscreen Overlays

Please Implement These Features, They Are ->VERY<- Helpful in Modding

**Comment by Blackout03** [comment]
Please create separate issues for features, and don't request things that have already been requested look through the issues to see already requested features

**Comment by Blackout03** [comment]
Fabric support will stay in the plugin
and we will not support rift due to it being illegal

**Comment by Blackout03** [comment]
also check the trello to see already planned features https://trello.com/b/DnFX9PnG/mctoolkit-roadmap

**Comment by Max094Reikeb** [comment]
> Entity Bases- Villager, Warden(for 1.17+) and Piglin

Villager is a feature request (new mod element) so don't dupplicate feature requests

> Spawn Egg Customization- Select Texture, Model

What do you mean by "model"? Spawn eggs don't have custom models, and selecting the base and dots color is already possible.

> Fullscreen GUI
> Progress Bars Linked to Variable
> Button Textures
> Vanilla Crafting Table GUI Template

> APIs

I don't know a lot of the APIs you marked so maybe they are not as useful as you may think?

> Patchuli Book mod element

Patchouli Book has an other way to be configured. It also has a wiki so it's not complicated. (there are also lot of tutorials)

> Animated Block

Animated blocks are already possible. Check in texturepacks how animated water texture is done.

> 3-D Model Creator

Blockbench is there for you

> Call 2 Procedures on single event

Already possible, in your first procedure, add a procedure block to call your second procedure.

> Custom Caves

Not possible as they are added in 1.17

> Custom Sky

Feature request already in GitHub

> Fullscreen Overlays

Unlike GUIs, Overlays are always fullscreen.

**Comment by tomiscool850** [comment]
i do agree with alot of this stuff well at least the packs stone pack adding new stones with the stairs and other stuff and the wool pack/color pack adding new color

**Comment by ApposModding** [comment]
Patchwork API- Github.com/PatchworkMC Patch Forge Mods to be loaded on fabric
