### ISSUE TITLE
Download Link not working

### ISSUE THREAD

**Issue by aurelierned** [Team-MCToolkit/MCToolkit#232]
This is a pretty small problem. When I try to download MCToolkit, a Link doesn't appear, and the place where the link should be appears as only text.
![Screen Shot 2021-01-28 at 10 31 30 AM](https://user-images.githubusercontent.com/78164424/106168540-02612480-6154-11eb-8a90-e91d9b76f243.png)

**Comment by Shadowdragon019** [comment]
There are NO snapshots, stable versions or other builds released. Please search a bit on MCToolkit's website, MCToolkit Discord server or this repository.

**Comment by Thediamondcryst** [comment]
Simple: The first snapshot's not even out.

**Comment by Max094Reikeb** [comment]
Before asking for something please **look on GitHub if the same problem has been reported**.
#140 #139
