### ISSUE TITLE
new stone pack

### ISSUE THREAD

**Issue by tomiscool850** [Team-MCToolkit/MCToolkit#233]
**Describe the feature**

I would like you guys to add a new pack called stone pack. this pack will be like the wood pack adding difrent types of blocks but with new stones

**How would you implement it?**

it would be next to the wood pack and it would be called the stone pack you can choose the name of the stone the color and how hard it is. it would add new stone cobblestone wall stairs slabs and recipes the recipes would include the coblestone stuff like slabs and stairs and walls  but it would also make a recipe for furnece and a furnece recipe to make the stone.

**Additional context**

mabey if you want you can also add a check that says "add smooth varent" witch will make the same stuff but smooth including the cracked and piller versions

**Comment by Goldorion** [comment]
Is the building pack tool not enough?

**Comment by tomiscool850** [comment]
oh I thought they would be diffrent dang and i thought it was a good idea
