### ISSUE TITLE
Child Model

### ISSUE THREAD

**Issue by CJDaBomb** [Team-MCToolkit/MCToolkit#234]
Ability to select the child model of an entity(if you want one) 

It would be an option in the entity class below the model and texture where you would checkmark a box to enable the child and have 2 dropdown boxes. One for the model and one for the texture

**Comment by Max094Reikeb** [comment]
Please respect the feature request template.

**Comment by Blackout03** [comment]
I mean it does follow the feature request template is just doesn't have the titles for the sections

**Comment by CJDaBomb** [comment]
> I mean it does follow the feature request template is just doesn't have the titles for the sections

exactly. quite a petty reason for closing the issue if you ask me
