### ISSUE TITLE
new time cycle feature

### ISSUE THREAD

**Issue by tomiscool850** [Team-MCToolkit/MCToolkit#238]
**Describe the feature**

this would add a whole new time of day for excample blood moon you could make a new time a day called blood moon

**How would you implement it?**

this would be a whole now element that would make a new time of day you can add when this day would happen the chance of it happinging 100% bieng the highest and would allways happen this would also have a entity spawing feture where diffrent entitys would spawn in this time

**Additional context**

just a thought you can also made a thing for how long this time lasts unless you want it to be 10 mins allways

**Comment by Max094Reikeb** [comment]
You can already do that with procedures. Just use the global trigger `on world tick update` and check the time of the day.

**Comment by tomiscool850** [comment]
but with this new feature yoiu can customize your new times alot more like spawns and other stuff

**Comment by Goldorion** [comment]
> but with this new feature yoiu can customize your new times alot more like spawns and other stuff

`You can already do that with procedures`
