### ISSUE TITLE
damage plus 2

### ISSUE THREAD

**Issue by tomiscool850** [Team-MCToolkit/MCToolkit#240]
**Describe the bug**

whenever a wheapon has damage it goes up by 2 for excmple if a sword has 4 dg on mcreator but then when you test its 6 dg

Please specify which mod elements to check in your workspace too, if applicable.

**Screenshots**

![image](https://user-images.githubusercontent.com/78148468/106374359-a656f580-6337-11eb-83e6-97ea38298108.png)
![Screenshot 2021-01-30 200907](https://user-images.githubusercontent.com/78148468/106374361-ad7e0380-6337-11eb-97aa-2fed3f2700ca.png)

**Comment by Goldorion** [comment]
Report this "bug" for MCreator because Klemen adds an additional value in the generated code.

**Comment by tomiscool850** [comment]
oh i thought it was a bug
