### ISSUE TITLE
wood tool pack upgrade

### ISSUE THREAD

**Issue by tomiscool850** [Team-MCToolkit/MCToolkit#241]
**Describe the feature**

the wood pack is amazing adding your new woods anytime but it missed a few things like buttons boats signs and preesure plates and finally crafting table recipe

**How would you implement it?**

this new upgrade for the wood pack would add the final pieces of the wood pack including pressure plates button signs boat trapdoor and door, and the recipes for thoughs and finally a crafting table recipe

**Comment by Goldorion** [comment]
Read the changelog. Already added a new pack maker tool.

**Comment by tomiscool850** [comment]
![image](https://user-images.githubusercontent.com/78148468/106493193-abb65c00-646d-11eb-85af-ffabd910c201.png)
yes but what is the even going to do
