### ISSUE TITLE
Complies but wont run.

### ISSUE THREAD

**Issue by LexShadow** [Team-MCToolkit/MCToolkit#242]
**Describe the bug**

All compiles fine no errors, but soon as we try go run it nothing happens, also wont run in the ide, even tho still no errors

**Steps To Reproduce**

Download git and follow the complie wiki > build > run

**Details**
 - MCToolkit version: Last source here from 3 days ago
 - OS: Windows

**Additional context**

The update from MCreator around the same time complies fine runs in both IDE and Build version, only your version fails to open, also you don't include any bat file like the other version does so unable to see if it's braking else where.

**Comment by Max094Reikeb** [comment]
Bug reports are only for functionalities. Are you sure you did configure a run configuration?

**Comment by LexShadow** [comment]
Yes I followed it to a T, I have redone it 3 times and not working I keep rebuilding the normal MCR one and this is working fine, I can't get it to run is IntelliJ ever, I not getting errors so I not sure where to go test from there I am little confused lol, I am open to all ideas.

**Comment by Blackout03** [comment]
well if it isn't working than you didn't follow https://github.com/Team-MCToolkit/MCToolkit/wiki/How-to-work-on-MCToolkit-using-Intellij-IDEA correctly

**Comment by LexShadow** [comment]
> well if it isn't working than you didn't follow https://github.com/Team-MCToolkit/MCToolkit/wiki/How-to-work-on-MCToolkit-using-Intellij-IDEA correctly

And clearly your not reading anything I have put and your been very rude, I have just confirmed I have Build the MCreator source fine, turn it and it works fine but your build what is almost the same did not build, I find it very rude of you to not read or just think or you must not of done it right, well I did, I tool the time to report it back to you from what I was able to do.

Even though many users are not able to do it right this is no way to reply to someone, I did follow it correctly 100% but it does not work this is the facts of the matter, when I have another moment I will give it another try but at this moment in time your build does not run under the same conditions as the core MCreator, what I built before and after trying your build!!

So to make this clear, I can build MCR fine it runs fine and it builds fine and runs stand along in exe installer and zip versions fine, your build as of the day of this post was not fine MCT didn't run, it DID build fine it did install fine all files downloaded and all code was there pretty as it should be, but didn't run or build.

I asked you to give me ideas to try debug it and fix it but you opted to be rude and say I didn't do something when I did, if you really want your build to take off when MCR leaves the scene you need to listen to all your bug reports even the silly ones, this is life and your making this for others not yourself and there for even if I didn't follow it right though I did it could mean a step or two might not of been clear, thought this isn't the case here all steps was followed to the letter.

**Comment by Blackout03** [comment]
If you followed it 100% correctly it would have worked

**Comment by LexShadow** [comment]
> If you followed it 100% correctly it would have worked

Well shows how much you know, the problem was git, every time I downloaded it via git it messed up but I cloned it via the IDEA and it now seems to load the main part of the tool, and I followed the same information as I did before you know why? it's the same for MCR, so for some darn reason the files was getting messed up on my normal git.

So if your going to be apart of the dev work please make sure you understand why something could go wrong, I still not sure why it's failing on the normal git version as that is how I also get the MCR version, but what's a fault else where, file corruption or file permission going for a wonder or even a bad sector on that part of the flash thought that's likely as flash don't save the same data to the same sector each time.

Though I see your public version lost all it's bells from the original posts you guys did.

Back to this matter, This wasn't user error, if a user as done tests and tasks to check this what you didn't offer then you can go down that rabbit hole of saying are you sure you followed the steps right, but when these steps are the same as another fork and that works 100% fine then we know something else is at foot.

Never point the finger at the user until all other options have been removed, I know some MCR users are still young and don't really know what they are doing, but some of us do and understand how the inners work, have A respect for users that thought well you test MCR and report back why not do it for MCT this isn't done for my fun this is to help both projects move forward.

**Comment by Blackout03** [comment]
well not my fault you didn't give any errors or anything... how are we meant to diagnose an error without any logs or anything

**Comment by LexShadow** [comment]
> well not my fault you didn't give any errors or anything... how are we meant to diagnose an error without any logs or anything

Once again, I told you this in the first post NO errors was posted not logs was created this is why I asked for ideas to debug what was going on, it is your fault on how you reply to someone also no one said it was your fault or anyone else fault, this is a app created to work on many different computers and in Java what is one hell hole at times to work with.

There wasn't any errors or logs created in the IDE, and well since you removed the bat file to debug the start up of the app I wasn't able to use that to see what if anywhere was it failing on start up, from what I could tell from my first test I did report in the discord when first downloaded it I got one error and it didn't come back but it said something about the splash screen been missing, if this file did become damages the this sure could be the problem but this happened once, on all clean recreates this error never showed again.

Just because no logs or errors was given to you does not mean the user didn't try see if there was any to give to you in the first place so yes the way your reacting to me is your fault.

I can't provide you something that wasn't created so a simple report does not mean the end user didn't put the time in, I spent 3 days trying to get this to work my side and I have done and I report back, maybe the rudeness of yourself fuelled that a little but point is I took my time to report this back, Also offers a clear alterative to download the files via the IDEA Git -> clone option

**Comment by Max094Reikeb** [comment]
@LexShadow 
1. It's clearly coming from you because I (and many other) never had any issues with this
2. Are you running MCreator or MCToolkit??? Because you said
> I have Build the MCreator source fine

So you builded the MCreator source fine or the MCToolkit source fine?

**Comment by LexShadow** [comment]
> @LexShadow
> 
> 1. It's clearly coming from you because I (and many other) never had any issues with this
> 2. Are you running MCreator or MCToolkit??? Because you said
> 
> > I have Build the MCreator source fine
> 
> So you builded the MCreator source fine or the MCToolkit source fine?

Well since I already reported back how it was fixed I can't create that bug so try that one again!

Also I build both MCreator and MCToolkit from source, multiple times MCreator built fine every time via windows git downloading it, but MCToolkit had this strange problem each time, I did report in your discord about the missing splash screen error on the first download but I redid that and it was gone the second time, but never would run or build and never had any exit errors or anything no log files, this wasn't a me problem.

This problem wasn't created by me, yes I faced this problem but saying I never had this problem means nothing in the world of computers, this as a dev can never taken as red and you have a lot to learn if your going to use that mindset, no two computers 100% the same in parts and install are the same there will always be something ready to gunk up the workings.

To also be clear I also tested this on my laptop what also got the same result when downloading via the windows git client, and also downloading the zip from git hub when I first reported it.

When I downloaded it today via the clone option in IDEA this worked, so I could of been githubs own file handling that day, a bit here or there going for a walk in most cases done stop apps from working but when it's from source it's another matter.

So I have built MCreator, Toolkit and a out of date fork from a friend just to test and all built fine MCreator and the friends files all started up fine and ran ok yours didn't open, with no errors back part from the one I reported the first import of the missing splash screen file though when looking at where it said it was missing the file was there.

Take the report as you will, I reported it, I wasn't in the wrong and I did follow the wiki fine as I have other forks working fine, Yes this bug wasn't created by you but this was found later and saying it's your fault your didn't follow it right is utter bull.

**Comment by willpill** [comment]
Instead of continuing this conversation, you could provide a video of how you set it up

**Comment by LexShadow** [comment]
> Instead of continuing this conversation, you could provide a video of how you set it up

Why would I do that? since it's already working only thing I changed was using windows git to the git built in IDEA this is made clear, why would I provide a video? who are you? 

The information is all in the wiki on how to set it up only think I would say it needs it get people to use the git in IDEA as it's all in one place and something went wrong with windows git.

**Comment by willpill** [comment]
I was just trying to help. If you keep that attitude you can guarantee no one will give any help whatsoever.

**Comment by LexShadow** [comment]
> I was just trying to help. If you keep that attitude no one will give any help whatsoever.

Once again, whom are you, you can try and help by reading, no one needs to provide a videos as the matter of what happened as been sorted it was a fault with windows git for some reason damaging a file, so your reply as no place here or anywhere? my attitude is fine thanks, I am not asking for help I was reporting a problem what was not the dev's fault in the end what is fine, so please read the hole post before you even comment, this was A, Winodw's, B, a git problem not the forks problem.

The problem was also fixed by using the IDEA(IDE)'s built in git clone option.

So I have no idea why you commenting or asked for a video when this post was for the devs and for them to better how they see people posting a report, though the same time I can see why they would comment since many of the MCreator users are younger and don't do what they need to do, so my point was they needed to not judge someone to the same standards.

Your comment though I am 100% lost why you asked for a video of a bug that I already said was fixed and this report was also closed so you really didn't need to even come to look.

**Comment by Max094Reikeb** [comment]
> So I have no idea why you commenting or asked for a video when this post was for the devs

@LexShadow wow! you're so rude! he was just trying to help! @willpill I also think providing a video could be a better way for him to show his problem.

**Comment by LexShadow** [comment]
I can't provide a bloody video of a matter that's not even shown and now since it's working why would I go back and undo it all, also he has not stated he has a problem he asked for a video of something that I no longer facing, I am not rude I am pissed off I took time out of my life to report this happening rather then finding your you all judged me and acted like I didn't know what I was doing and didn't follow the wiki THAT is rude, so before you ever come and call me rude again check yourself in the mirror I didn't have to pop back and post anything for you.

Now if this matter pops up again you have a option to ask someone to tried, you welcome!

Part from that I am done with this, I really feel like I am trying to ask my kids to clean there bloody room in how backwords some of these replies have been.

Good day.

**Comment by Max094Reikeb** [comment]
> I can't provide a bloody video of a matter that's not even shown

So you can't provide a video of you downloading the Git code of MCToolkit?

**Comment by Max094Reikeb** [comment]
> and now since it's working why would I go back and undo it

so is it working or not? if it's working now, why didn't you say "it works now, I did a bug report for nothing"?

**Comment by willpill** [comment]
Let’s just stop on this issue if he refuses to cooperate

**Comment by LexShadow** [comment]
OK it seems no one is reading so 
"the problem was git, every time I downloaded it via git it messed up but I cloned it via the IDEA and it now seems to load the main part of the tool,"

This statement right here is saying there was a problem what the problem was and now it's loading it like it should, I am little lost what you can't get from that.

Why would I post a video of me downloading it? I don't understand that logic, since I already made it also clear I have the MCR version working 100% fine,.

She thanks and I have already cooperated, you guys are the ones that didn't read and judged something without knowing any facts I even posted what I did to get it to work!! so ya leave this issue in the past but LEAVE it here, as I was very clear with what was up and how to fix it, so others whom might have it can read it them selves as you clearly didn't want to even help on the matter and wanted to say I didn't follow the bloody wiki well, you was clearly wrong.

Thought the MCR version seems to work better so for now I will just keep building that one since it worked first time and your version don't even have all the changes you all posted on your discord, good luck with the project.
