### ISSUE TITLE
Exe cannot run

### ISSUE THREAD

**Issue by TeamRIS** [Team-MCToolkit/MCToolkit#245]
Windows 10 Pro
AMD Ryzen 5 3600
16GB ram

The exe created by the command exportWin64 does not run

**Comment by Thediamondcryst** [comment]
I am not a dev, but I can sure say that your issue doesn't follow the template they provided.

**Comment by Max094Reikeb** [comment]
As I said in #242, bug reports are about the software itself. Why would you even try to export MCToolkit as an app? If you want to use it just launch it from IntelliJ... and thx @Thediamondcryst is right, for future bug reports, respect the template.

**Comment by Thediamondcryst** [comment]
I know a thing or 2. :)
You're welcome.
