### ISSUE TITLE
Ranged Weapon Animations & Base Ranged Weapon Types

### ISSUE THREAD

**Issue by SacreDZ1** [Team-MCToolkit/MCToolkit#248]
Ranged Weapon animations such as as the bow pulling and crossbow pulling or new base type system.

When selecting the ranged weapon element type, after entering the registry name, another GUI option shows asking if you would like to use a item base, such as Bow, Crossbow, Spear or Custom (The system we have now.)

Each type would act like its respective base game counter part such as the bows charging up to fire and its corresponding power depending on how long u held right click, crossbow with the loading a shot time and right click to fire after its loaded and the spear, holding to throw and then it being removed from inventory after thrown, also being retrievable from the ground afterwards. 

This would also allow for each specific ranged item type to use the vanilla enchantments as the weapon type will be defined in the code.

**Comment by Max094Reikeb** [comment]
Please respect the feature request template.
