### ISSUE TITLE
"Mob States"

### ISSUE THREAD

**Issue by PyroBoo** [Team-MCToolkit/MCToolkit#255]
**Describe the feature**

An interesting and useful addition to the creation of mobs in McToolkit would be what, from now on, I'm going to refer to as "Mob States". Basically, different states a mob can be in, like walking, swimming, flying and so on. You'd be able to have mobs walk around and then, during the night, go to sleep. Or perhaps wander but fly away when they come near. Maybe something that attacks at range on the ground, but swoops down mid-flight.

**How would you implement it?**

They way I'd implement such a feature would be to let creators define different Mob States: They would have a name associated with them (of course, no duplicate names), a model+texture (or models, and maybe even let creators modify the texture of the mob based on the state), an AI Tree (one associated to each different mob state) and triggers (basically, procedures) to define when the mob should enter the specific state. 

**Additional context**

I am fairly sure that this has either been requested before or is super hard/half impossible/very much time-consuming to implement, but it would be kind of cool and would make mobs made with McToolkit a bit more interesting and would give mod makers more tools to customize the game as much as they like.

**Comment by Goldorion** [comment]
Entity models and textures don't work the same way as blocks. It's much harder to make and we can't make "entity states" like we talk for blocks.
