### ISSUE TITLE
A If Statement procedure block

### ISSUE THREAD

**Issue by hawkishnes** [Team-MCToolkit/MCToolkit#260]
**If Statement**

This would be a block that would have a selected were you’d be able to select from the following:
1. If
2. If Not
3. If Has any value
4. If does not have any value

You could add more but those are what I came up with. You would have an input and then that selected and then another input. Then attached to the block you would put output code. The output code would output only when the stamens is true.

**Implementation**

[Here is a picture showing how I would implement it.](https://drive.google.com/file/d/1O813UvbU2PVrQ0kZg2fPeXii3B-SrcRr)

**Additional context**

I would like to have an otherwise part to, please. I am requesting this feature because I would really use it in my mods that I make using MCreator and after enough features might switch to MCToolkit.

**Comment by Max094Reikeb** [comment]
All of these already exist. You have the if / else if / else statement, you also have a "not" procedure block (to make for example "if not NBT number tag of event/target entity = 3".
All the things your said can already done with existing procedure blocks.
