### ISSUE TITLE
GUI mob preview

### ISSUE THREAD

**Issue by mumke** [Team-MCToolkit/MCToolkit#261]
I've seen in many mods that certain GUIs(especially from mods with a lot of mobs) present mobs in the same way you see the player model in the inventory

I would like to have an option of adding an "entity preview",again,that is in a similar manner to the player model from the inventory

Now regarding the UI,this option would probably be similar to an image in the GUI editor,but its instead generated by a button wich gives you the option to select any entity available

I've attached below an image that explains what im talking about(screenshot from Alex's mobs mod)
![fOOEsCl](https://user-images.githubusercontent.com/71014103/110962790-063eb400-835a-11eb-963b-aaf6c1ca8d1b.png)

**Comment by Max094Reikeb** [comment]
Please respect the feature request template.

**Comment by Luli252** [comment]
i think its is a nice idea
