### ISSUE TITLE
Vanilla unstackable item recipes cannot be removed/replaced.

### ISSUE THREAD

**Issue by AAli107** [Team-MCToolkit/MCToolkit#272]
**Describe the bug**

In MCreator, there's a bug where tools or unstackable item's original recipes cannot be removed/replaced.

**Steps To Reproduce**

1. Get into any workspace.
2. Create a recipe element called "StoneSword" registry: stone_sword
3. In the recipe element, change the namespace to Minecraft
4. Make sure the registry name is set to the vanilla name e.g. stone_sword
5. Add in all the recipe slots, air blocks.
6. Save and Test. This is supposed to remove the recipe, but the recipe still works.

Please specify which mod elements to check in your workspace too, if applicable.

Recipe Mod element

**Details**
 - MCToolkit version: MCreator 2020.5
 - Generator type: [e.g. forge-1.15.2]
 - OS: Windows 10

**Comment by Max094Reikeb** [comment]
While MCreator is not over, bug reports aren't allowed. Please open the bug report on MCreator GitHub.
