### ISSUE TITLE
Renaming Folders

### ISSUE THREAD

**Issue by DoltenBolten** [Team-MCToolkit/MCToolkit#274]
**Describe the feature**

If this feature is added, it would let players rename workspace folders

**How would you implement it?**
It would be a new button in the "Folder Actions" section 
![image](https://user-images.githubusercontent.com/66805168/113316288-2966de80-92dc-11eb-84a4-eafb063d9be0.png)

**Additional context**
None

**Comment by LoicMaitreDuFeu** [comment]
alright

**Comment by LoicMaitreDuFeu** [comment]
was planning to put that on MCreator, will put that on both

**Comment by Max094Reikeb** [comment]
This is already added in MCreator.
