### ISSUE TITLE
:: Emoticon/Emoji Commands(Website)

### ISSUE THREAD

**Issue by MrCreeps** [Team-MCToolkit/MCToolkit#275]
**Describe the feature**

Commands to create different emoticons/emojis used :: (example :awesome:) 

**How would you implement it?**

When typing : on the website (anywhere you can type) you will have a list of suggestions. These can be exclusive to donators to add an incentive to donate to MCToolkit.

**Additional context**

This could be a cool thing to add to the MCToolkit website.

**Comment by Max094Reikeb** [comment]
The GitHub is only used for feature requests in regard to MCToolkit's software, not its website.

**Comment by MrCreeps** [comment]
Am I allowed to post website feature requests on the forums?
