### ISSUE TITLE
Customizable Profile Background (Website)

### ISSUE THREAD

**Issue by MrCreeps** [Team-MCToolkit/MCToolkit#276]
**Describe the feature**

Be able to upload an image for the background of you MCToolkit profile page.

**How would you implement it?**

When in account settings, under the avatar picture, you can upload a picture of a custom background. It would replace the faded background of your avatar. This could be exclusive to donators to incentivize donating to MCToolkit. 
![image](https://user-images.githubusercontent.com/75145015/115914054-0771ff00-a437-11eb-8ce9-48dac5db5b3d.png)

**Additional context**

This could add to the customization to MCToolkit.

**Comment by MrCreeps** [comment]
Is there a place where I can suggest things for the website?

**Comment by Lego245** [comment]
i think that you can leave a topic [here](https://mcreator.net/forum/431) to suggesting ideas for the website

**Comment by MrCreeps** [comment]
The only thing is that the Website and community discussion is for MCreator, not MCToolkit.
I have a whole list of things for the MCToolkit website that would be cool to see.

**Comment by Goldorion** [comment]
> 
> 
> Is there a place where I can suggest things for the website?

It's ok to post them on this tracker, but we will just close them when we see them as this is not a tracker for the website. We will then, give the feature to our website developers.
