### ISSUE TITLE
Procedure blocks become frozen with a build error

### ISSUE THREAD

**Issue by joseph8675309** [Team-MCToolkit/MCToolkit#277]
I was making a procedure and I needed a piece from the premade get in 6x6 box in the procedure template tab, I deleted 2 of the local variables and after I tried to move the blocks nothing would happen and only until I exited the procedure via the X next to the tab did things work normally.

MCreatorEAP20211b12313

**Comment by Goldorion** [comment]
Report MCreator bugs on the MCreator’s issue tracker. Also, provide more details next time.
