### ISSUE TITLE
bucket item for recipes

### ISSUE THREAD

**Issue by tomiscool850** [Team-MCToolkit/MCToolkit#279]
**Describe the feature**

when making a new fluid in the recipe elements there's only the fluid block, but with my feature you can make a new fluid but and get the bucket and block in the recipe element making it so people can make recipes with fluids without cheating.

**How would you implement it?**

all you have to do is make a new fluid and as long as the bucket with the fluid is checked then you will get both the block of the liquid like every fluid but you will also get the bucket item like random example acid bucket so you can make recipes with that acid liquid

**Comment by Max094Reikeb** [comment]
Using fluid buckets in recipes is now possible with MCreator. It will therefore be possible with MCToolkit when we start working on it.

**Comment by tomiscool850** [comment]
yup now im happy
