### ISSUE TITLE
sound procedure blocks

### ISSUE THREAD

**Issue by tomiscool850** [Team-MCToolkit/MCToolkit#281]
bacicly its a new procedure block where it would add a sound procedure block. for excample,  a block it right clicked on you can put the new sound procedure block and choose the sound and boom when you right click on the block it will the the sound

the new block would be under a new catigory sounds under logic. the block would say play sound, then you choose your sound. it can be custome or already in minecraft. 

**Additional context**

i feel this is a good feature becuase it would make more customizasion when it comes to new block placements and other things

**Comment by suckinsyn** [comment]
![image](https://user-images.githubusercontent.com/17712352/117346191-bab30d00-aea7-11eb-9855-7406a1bd0696.png)
Isn't this the procedure block you're describing?

**Comment by tomiscool850** [comment]
wait its already in the game

**Comment by Max094Reikeb** [comment]
> wait its already in the game

Indeed. Next time, I advice you to make sure what you're requesting is not already in MCreator / MCToolkit.
