### ISSUE TITLE
Tweak ideas

### ISSUE THREAD

**Issue by Nosferatu8** [Team-MCToolkit/MCToolkit#282]
1st we can't lock/unlock elements so we can just accidentally moving away our images texts etc. I guess an lock/unlock feature should be pretty usefull for placed elements in the GUI.

2nd - Which I don't know that it is a bug or a feature but every time when I save a GUI and open it again, the original GUI texture just reseting itself to the original size so I always have to change it back.

3rd - The original background texture forced generation is annoying. Before releasing a snapshot to my mods I always have to delete these textures (since i'M using my own textures) otherwise these unused basic vanilla looking backgrounds just holding space for nothing. I understand in some point why it is important to generate it every time but if you guys should make a checkbox in order to let the players decide about the generation of the vanilla like background texture that would be really nice.

4th - Adding GUI elements are so slow. We always have to scroll trough a bunch of variables and sometimes even trough graphical elements to find the one what we needed. I know that the image selector has a search function but it would be nice to have the same texture selection for entities and GUI images as the item and block texture selector with the search bar. Much more practical and easy to overview what we've got to work with. 

5th - Adding a better variable selector. I've got like 300 variables now and it's literally nearly impossible to keep searching manually for each one of the variables. Making a totally new variable selector like an opening window with the list of the variables and with a search bar should also make things easier for larger mods. The same can be done to the procedure editor "Call Procedure" element since having a lots of procedures can slow down the searching on the list the more elements you've got.

6th - Entity modell selector should have a better way or a search function because the same problem is standing as in the previous problems. We have to scroll a lot.. its just annoying, not deadly but could be better :) also why it is put the word "Model"xy before all of the imported custom entity models? 

7th - More interaction with the GUI slots. It's really cool that we can now have much more options and we can set up procedures in certain conditions but we should have some sort of a new procedure element or something like that in order to controll the players that on what condition can they take out the items from a slot. For example this one should be usefull for a shop GUI. 

8th - Adding DTM's Toolkit plugin as a basic feature. 
I think I don't have to explain much about this. Changing attribute modifiers for the player and other entities are the essential part of an RPG mod. And I think that many people like to have such an option in their procedure editors since most of the mods are fantasy themed :) 

Well this is my .. small... list or not that so small. I hope I was not rude or anything these are only ideas and tips how to make MCreator even more better :) It's really great but it should be improved more and become more easy to manage or make better and more interesting mods with some of these small tweaks. 

Thank you for reading it :)

**Comment by Max094Reikeb** [comment]
Please respect the feature request template. If you have several ideas then make several feature requests.
