### ISSUE TITLE
New option to make block behave like vine

### ISSUE THREAD

**Issue by Max094Reikeb** [Team-MCToolkit/MCToolkit#29]
**Describe the feature**

There is already an option to make block function like a ladder, but it requires a block behind to we can climb on it (like actual ladders) so it would be nice to have a new option to make block function like vine (like the new vines in 1.16.X) which does not require a block behind to be climbed

**How would you implement it?**

It would be a new option in blocks properties.

**Comment by AlsoSomeoneElse** [comment]
I'm positive this is because they changed how climbable blocks fork in 1.16, not because of special code for vines

**Comment by Max094Reikeb** [comment]
I'm closing this because it can be done. You need to make your block/plant able to be traversed by the player, and then, add your block to the `minecraft:climbable` tag.
