### ISSUE TITLE
built in mob editor that can easily cross over and function together with blockbench and blockbench models

### ISSUE THREAD

**Issue by ItzSemoxx** [Team-MCToolkit/MCToolkit#291]
**this feature would simplify making entities and 3d rendered models and custom blocks with double layers or maybe even three layers and it could help with making plant textures and custom mushroom like objects or something like a torch**

it would be its own tab or function in the implemented in the living entity mod element right next to the select model button you would then have to click a + icon and it would then proceed to give you the option of  creating your own model using the built in function and/or you could choose  one of two alternative options where you could merge two models or use already existing models from minecraft like a creeper or both options in one where you could implement models form your own creation and fuse/merge them with the already existing minecraft model and that would create endless ammounts of creation options. 

**it should also grant the dev/creator/user of program to combine models together like merge a mushroom with a red and white textured cow model and bam you have a mooshroom**

you could find your own way of implementing this or you could just make it a little different, but if you were to implement a feature like this atleast keep the main idea and functionalities alive and available
thank you for reading

**Comment by Goldorion** [comment]
It's already in our Trello.
