### ISSUE TITLE
structure building made easier

### ISSUE THREAD

**Issue by ItzSemoxx** [Team-MCToolkit/MCToolkit#292]
**it would be a new built in editor where you have a template ground based in the biome you selected to be a template ground floor and on this template you would be able to build stuff using blocks and items from minecraft and just customs made by you 
and to make dungeons easier you could also use a chest as building block that in game would work as a chest and you could then add a loottable to the chest by double clicking it/right clicking it before selecting the chest from creative tab
you could also make multiple structures on this selected floor template which would be how you make villages you could then resize the floor template to be bigger and you could make mobs spawn by selecting it in a new entitie spawning tab inside of the built in structure editor for example if you wanted a village you would need villagers so you would add a villager mob/entity to spawn in a certain size this would be a work around for not having to use structure blocks and structure void blocks **

new built in editor of which you would acces through + icon next to structure select inside of the mod element structure spawn

thanks for reading

**Comment by Goldorion** [comment]
Minecraft + sructure blocks
