### ISSUE TITLE
just improve Custom dimensions mod element

### ISSUE THREAD

**Issue by ItzSemoxx** [Team-MCToolkit/MCToolkit#293]
it would be nice if we would have a way to select an already existing minecraft  item or custom item to use as portal igniter

it would make it way more survival friendly 
it would also be cool to add more customization options to custom biomes and dimensions and a better way to fuse the two mod elements and a way to edit the world gen of already existing dimension including the overworld 
and a way to craft a custom portal igniter item to use in survival playstyle

**Comment by Goldorion** [comment]
On feature per ticket, please
Also, we will remove this fork soon as we are moving all announced features to MCreator. We will re-fork it when we will begin to work on the first update.
