### ISSUE TITLE
Item Spawn

### ISSUE THREAD

**Issue by LucyNoel** [Team-MCToolkit/MCToolkit#294]
Describe the feature

You would be able to choose where your items spawn. For example if you want your item to spawn in a chest in a certain type of  village, or just in a random village or village's it could. Or If you wanted your item to spawn in a custom  mod element or place  like a biome or dimension it could.

How would you implement it?

It would be options within the item mod element editor.

**Comment by Max094Reikeb** [comment]
You can only do that with loot tables. As for making your item spawn in a biome or a dimension, I don't understand what you mean but it's surely already possible...

**Comment by LucyNoel** [comment]
Oh Sorry
