### ISSUE TITLE
Books

### ISSUE THREAD

**Issue by LucyNoel** [Team-MCToolkit/MCToolkit#295]
Describe the feature

The ability to write books that would spawn in your world, be given to a character when the spawn or die, or be crafted.

  How would you implement it?

As a new mod element.

**Comment by MASTRIO** [comment]
you can just make a GUI open when you right click an item, no need for a new mod element

**Comment by LucyNoel** [comment]
I mean you write the book in MCreator then it spawns in that place or time.

**Comment by DoltenBolten** [comment]
This can be achieved using an item mod element and some simple procedures, no?

**Comment by MASTRIO** [comment]
yep, there is no need for a new mod element, it's already completly possible
