### ISSUE TITLE
MCToolkit Spam Bots

### ISSUE THREAD

**Issue by MrCreeps** [Team-MCToolkit/MCToolkit#296]
Hello,

Currently on MCToolkit there are HUNDREDS of spam bots creating accounts and flooding the members list. If you check the members list right now you will see many things about casino vacations and skin care routines just to name a couple. Most of these bots registered today and I want to bring this to the website and moderator's attention. If you are reading this, it is most likely outdated. I posted this here since there is no Website or General discussion forums on MCToolkit as I am posting this.

This was copied from my forum topic on the MCToolkit website. This should be pretty urgent since this goes against 2 parts of the community guidelines, spam and inappropriate/sexual conduct since one of the spam bots is has an inappropriate profile picture.

I couldn't really find a way to make this fit into the template, sorry.

![image](https://user-images.githubusercontent.com/75145015/119712255-06f9c900-be26-11eb-9e82-ec4f3c537f7d.png)

**Comment by Max094Reikeb** [comment]
> I couldn't really find a way to make this fit into the template, sorry.

GitHub is not about the website that's why.
