### ISSUE TITLE
Checklists And Notes

### ISSUE THREAD

**Issue by LucyNoel** [Team-MCToolkit/MCToolkit#297]
Describe the feature

The ability to write Checklists and notes for your mod.

  How would you implement it?

   It would be a feature that you could access anywhere on the software.

  Additional context

People could use it if the had A idea for their mod and the needed to write it down quickly or if they wanted to remember what they need to do in their mod and want to plan it out.

**Comment by Max094Reikeb** [comment]
There are many softwares in your computer to do that. No need for a new feature...

**Comment by MrCreeps** [comment]
I use Trello for my mods.
