### ISSUE TITLE
Trades

### ISSUE THREAD

**Issue by SirreStrange** [Team-MCToolkit/MCToolkit#305]
**Describe the feature**

A new mod element that allows you to add villager trades to a certain profession

Features:

**Villager Profession** 

**Item 1 --> Amount**

**Item 2 --> Amount** (Optional)

**Item that you get --> Amount**

**How would you implement it?**

Mod element

**Additional context**

I do not think villager trading is hardcoded so you may be able to add it

**Comment by Max094Reikeb** [comment]
Duplicate of #58 and #151

**Comment by SirreStrange** [comment]
Ah.. Sorry, I saw the Issues but I must have misread them, I thought they were different
