### ISSUE TITLE
Upon the Fabric Generator Rewrite, merging it with MCToolkit

### ISSUE THREAD

**Issue by SlayDigger** [Team-MCToolkit/MCToolkit#32]
**Describe the feature**

When the Rewrite for the Fabric Generator is finished, merging it with MCToolkit as an integrated plugin.

**How would you implement it?**

Just make the compiled fabric generator come part of the download within the plugins folder

**Additional context**

should be easy considering Goldorion made it...

**Comment by Goldorion** [comment]
I didn't work on the fabric generator since BoogieMonster updated it in 1.16.x and re-wrote it. I already asked it one day, and he didn't seem to want to merge for the moment.

**Comment by CrispyChips6660** [comment]
The fabric generator is currently very unstable and buggy.
We won't be merging any time soon.
