### ISSUE TITLE
Brewing stand recipes

### ISSUE THREAD

**Issue by LucyNoel** [Team-MCToolkit/MCToolkit#33]
Describe the feature

This feature would give you a new recipe option for potions.

How would you implement it?

There would be a new option for a brewing recipe in the recipe type choices located in the recipe element option. The recipe would be connected to the brewing stand because that's where you make potions. Just like a smelting recipe is connected to the furnace.

**Comment by Max094Reikeb** [comment]
Brewing stand recipes will be added in MCreator...
