### ISSUE TITLE
Generator for all block types based on a single texture input.

### ISSUE THREAD

**Issue by Max094Reikeb** [Team-MCToolkit/MCToolkit#37]
**Describe the feature**

It would be better to be able to generate a block will all its bases (stairs, slabs, ...) with one shot (and their recipes ofc)

**How would you implement it?**

It would be a generator based on a single texture input. It would generate stairs, slabs, normal block, door, sign, etc. from one single texture.

**Comment by Max094Reikeb** [comment]
@Goldorion could you do it? You're familiar with generators (you made a wood one)

**Comment by Goldorion** [comment]
I can, but I don't know when I will make it because it's really long to code.

**Comment by Goldorion** [comment]
You should now be able to make it with my new JSON system. Check the tool and the wood pack makers.

**Comment by Max094Reikeb** [comment]
Indeed...
