### ISSUE TITLE
Get last posted message procedure block

### ISSUE THREAD

**Issue by scorpion981** [Team-MCToolkit/MCToolkit#4]
**Describe the feature**

I want a new **procedure block** that get the last message posted by a player in the general chat. 

**How would you implement it?**

Maybe in the category world data or in the category player data to get the last message he posted instead of all the messages already. The two work for me.

**Comment by Goldorion** [comment]
Please use the template.

**Comment by scorpion981** [comment]
I did everything that it was wanting me to do

**Comment by Max094Reikeb** [comment]
It can already be done. You can create a procedure that is triggered every time a message is posted. Then, you save the message into a global variable. This variable will be modified every time a message is posted then, and you just need to call it to get the last posted message.
