### ISSUE TITLE
Procedure block to check for entity category

### ISSUE THREAD

**Issue by Max094Reikeb** [Team-MCToolkit/MCToolkit#40]
**Describe the feature**

Some stuff like enchantments are only applicable to a category of entities. Like "Arthropod" or "Undead" or "Illager", ...

**How would you implement it?**

It would be a procedure block, and maybe we could add an option in the entity mod element to put a custom entity in a category.

**Comment by CrispyChips6660** [comment]
Don't we already have entity type settings?
a procedure block could be useful tho

**Comment by Max094Reikeb** [comment]
It turns out that the procedure block to check for entity category (or type) already exists...
<img width="409" alt="Capture d’écran 2020-12-20 à 13 02 36" src="https://user-images.githubusercontent.com/49318596/102712773-cd93bf00-42c3-11eb-9ec6-7f19d6cc5b67.png">
