### ISSUE TITLE
Custom liquid recipient support

### ISSUE THREAD

**Issue by Max094Reikeb** [Team-MCToolkit/MCToolkit#42]
**Describe the feature**

A custom fluid cannot be placed in a Cauldron or a Bottle yet, it should be possible.

**How would you implement it?**

It would be a new option in the fluid mod element.

**Comment by Max094Reikeb** [comment]
Impossible to make: cauldrons are hardcoded with Water.

**Comment by Blackout03** [comment]
would this be possible in 1.17 since it is getting lava cauldrons?

**Comment by Max094Reikeb** [comment]
> would this be possible in 1.17 since it is getting lava cauldrons?

No, even in 1.17 they just add lava and snow to the code, it's still hardcoded to water, lava and snow.

**Comment by Blackout03** [comment]
ok
