### ISSUE TITLE
New trigger for when item is enchanted

### ISSUE THREAD

**Issue by Max094Reikeb** [Team-MCToolkit/MCToolkit#45]
**Describe the feature**

We should be able to trigger a procedure when we enchant an item.

**How would you implement it?**

It would be a simple procedure trigger.

**Comment by titedog** [comment]
This is a really good idea.

**Comment by Max094Reikeb** [comment]
After lot of research, I don't think it's possible. The event is not registered in Minecraft or in Forge.
