### ISSUE TITLE
Better Installation System

### ISSUE THREAD

**Issue by SlayDigger** [Team-MCToolkit/MCToolkit#46]
**Describe the feature**

I wish for MCToolkit to be installed more simply and easily.

**How would you implement it?**

Instead of installing a .zip, when installing the windows version of MCToolkit providing a .msi, which installs the files for the most recent stable version from a git repository / server 

**Additional context**

Perhaps .pkg on mac and any kind of appimage on linux

**Comment by Goldorion** [comment]
It's already possible to download the installer. He's only available for the stable versions though.
