### ISSUE TITLE
Enchantment Procedure Crashing

### ISSUE THREAD

**Issue by TheDerpySupport** [Team-MCToolkit/MCToolkit#53]
I had made an enchantment in Mcreator Version **EAP 2020.5 b39514** called Immolation, It uses the **Does Entity Exist** procedure block to detect if there are monsters within a 2 block radius around the player along with **Get Nearest Entity** to deal AOE damage to those monsters. 
![image](https://user-images.githubusercontent.com/21302014/98572730-f5831200-2283-11eb-97b8-50b7157fd007.png)
You can see it in this image. 

It was working in that version however upon updating to **EAP 2020.5 b43719** and launching the client simulator it would crash. Applying the enchantment on armor via anvil and getting near monsters would crash the client.

Steps to Reproduce: 
1. Make the procedure in **EAP 2020.5 b39514**
2. Save the workspace
3. Update to **EAP 2020.5 b43719**
4. run client
5. apply enchantment and walk near monster entities

**Comment by Max094Reikeb** [comment]
1. You did not respect the bug report template
2. There is no log for your crash report
3. Post bug reports in MCreator GitHub until MCreator is not over.
