### ISSUE TITLE
Custom step sounds for block creation.

### ISSUE THREAD

**Issue by SuperMarioSega** [Team-MCToolkit/MCToolkit#55]
**Describe the feature**

This feature would give us the option to choose a custom step sound of a block from your own imported sounds.

**How would you implement it?**

This would be a new option within the step sound drop down list.

![custom](https://user-images.githubusercontent.com/49171078/98619081-7d8f0900-22d0-11eb-9279-9f6faabc0d81.PNG)

**Comment by Max094Reikeb** [comment]
Please respect the new feature template. I'll reopen the issue when you'll change it.

**Comment by SuperMarioSega** [comment]
> Please respect the new feature template. I'll reopen the issue when you'll change it.

Could you maybe explain to me a bit more about what you mean? As this is indeed a request for a new feature.
If I have posted in the wrong area, please notify me about that and I'll change it as soon as possible.

**Comment by Max094Reikeb** [comment]
It's okay now, you changed your post.

**Comment by SuperMarioSega** [comment]
Oh great, much appreciated.
