### ISSUE TITLE
Adding a way to know the translation percentage when selecting a language

### ISSUE THREAD

**Issue by Max094Reikeb** [Team-MCToolkit/MCToolkit#56]
**Describe the feature**

Some languages aren't fully translated. So it would be useful for users to know the percentage of translation of the language they select when they change it.

**How would you implement it?**

When saving the preferences, we could check if the user changed his language, and if yes, then display a little window to tell him something like this : 
`Information : you selected language <language> which is X% translated. Some strings may still be in english or inaccurate. You're always welcome to contribute to MCToolkit translation in Crowdin (https://crowdin.com/project/mctoolkit)`

**Comment by Defeatomizer** [comment]
You should also be able to check if certain "translated" strings are actually copies of the original text.

**Comment by Goldorion** [comment]
The easiest way to implement that would be to use the Crowdin API I think. I'm trying to understand how to use the [API v2](https://support.crowdin.com/api/v2/#section/Introduction)

**Comment by Max094Reikeb** [comment]
This was added in MCreator. Closing.
