### ISSUE TITLE
Several bugs moving from old workspace into MCToolkit 2020.6

### ISSUE THREAD

**Issue by Max094Reikeb** [Team-MCToolkit/MCToolkit#60]
**Describe the bug**

I tried to move an old workspace (from MCreator 2020.4) into the most recent version of MCToolkit (the one from GitHub) and I encountered a lot of errors in the console.

**Screenshots**

I have a lot of screenshots indeed...
<img width="1336" alt="Capture d’écran 2020-11-10 à 14 49 17" src="https://user-images.githubusercontent.com/49318596/98685035-2ee07e00-2367-11eb-996f-1c206ab09f0e.png">
<img width="1336" alt="Capture d’écran 2020-11-10 à 14 52 38" src="https://user-images.githubusercontent.com/49318596/98685054-356ef580-2367-11eb-8b9b-257f12c2f2cf.png">
<img width="1336" alt="Capture d’écran 2020-11-10 à 14 54 40" src="https://user-images.githubusercontent.com/49318596/98685064-37d14f80-2367-11eb-9559-9b169312a40b.png">
<img width="1336" alt="Capture d’écran 2020-11-10 à 14 55 05" src="https://user-images.githubusercontent.com/49318596/98685080-3a33a980-2367-11eb-9540-806918f975dd.png">
<img width="1336" alt="Capture d’écran 2020-11-10 à 14 55 27" src="https://user-images.githubusercontent.com/49318596/98685085-3c960380-2367-11eb-97ac-940314465ffe.png">

**Details**
 - MCToolkit/MCreator version: [2020.6]
 - Generator type: [e.g. forge-1.15.2]
 - OS: [e.g. Mac]

**Comment by Shadowdragon019** [comment]
Which workspace is this? Is it the one I gave you via Google Drive today?
If so it may be Plug-Ins causing errors but I'm not sure as I don't know much about coding.

**Comment by Max094Reikeb** [comment]
Yes, it was this one. Were you using any plugins with it?

**Comment by Shadowdragon019** [comment]
Yes I was. I'll send a screenshot of them in a moment.

**Comment by Shadowdragon019** [comment]
![Screenshot (1267)](https://user-images.githubusercontent.com/67480398/98686062-bf01d180-232d-11eb-8dd0-745282f3b1b8.png)
The ones in white are the not-default-MCreator ones.

**Comment by Max094Reikeb** [comment]
Wow you have a lot of plugins, this will be hard for you to move to MCToolkit...
Anyways, thx for your participation. I guess I can close this issue.

**Comment by Shadowdragon019** [comment]
You're welcome!
