### ISSUE TITLE
Fireproof/Lavaproof Option for Items

### ISSUE THREAD

**Issue by titedog** [Team-MCToolkit/MCToolkit#61]
**Description:**
The feature would add 2 new checkboxes to any kind of item element (Item, Food Item, Ranged Item, Tool, etc.) which would be "Fireproof" and "Lavaproof"
Fireproof would work like Netherite when it doesn't burn in fire, and Lavaproof would work the same, but just toggle if it could be burned by lava.
**Alternatively**, you could add just one option called "Fireproof" which would prevent it from burning up to any kind of vanilla fire/lava source. This may be how you have to implement it due to the code which prevents Netherite items from burning (or it might not, I have not looked at the code).

**Comment by Blackout03** [comment]
This will be added once 1.16 gets added to MCToolkit. at the moment this is impossible.

**Comment by CrispyChips6660** [comment]
yea 1.16 just adds a simple method to the item constructor to do this, it would be simple to add once we update but for now it's impossible

**Comment by Max094Reikeb** [comment]
Now that 1.16.4 has come to MCToolkit and MCreator, this will surely be added...

**Comment by Goldorion** [comment]
It will be added with MCreator 2020.6/2021.1.
