### ISSUE TITLE
Custom Villages

### ISSUE THREAD

**Issue by PlantStar-Alpineer** [Team-MCToolkit/MCToolkit#65]
**Describe the feature**

The ability to create custom modded villages. The following parameters could be:

- The structures used
- Amount and density of structures
- Percentage of the village that is each structure
- What mobs live in the village
     - Amount range of each mob in each structure
- Path width and composition
     - Composition pattern and intersection design if necessary
- Which side of each structure should face the path
- Biome and dimension restrictions
- Whether structures should be fenced
     - The fence used
- Distance of structures from path
- Whether there should be a "driveway" connecting the structure to the path it's facing
     - Composition of the driveway
     - Composition pattern if necessary
- Which structure(s) can occur at the intersection of paths
     - Probability of each intersection structure appearing
- Whether the village should be walled
     - Structures used for sides and corners

**How would you implement it?**

I haven't tried to implement it, but I think this could work as a new mod element.

**Comment by Goldorion** [comment]
It's "already" possible with Jigsaw blocks. However, there is currently a bug with them that doesn't allow us o use them, but I don't know if Mojang fixed the bug when they re-code the generation in 1.16 and 1.16.2 I will have to test when MCreator will have a 1.16.4 Forge generator. If the bug has been resolved in 1.16.x, we won't have to create a new mod element as the Jigsaw block makes everything needed.
