### ISSUE TITLE
Custom Honey/Slime Block Bases Extra Option

### ISSUE THREAD

**Issue by titedog** [Team-MCToolkit/MCToolkit#69]
This feature would be an extra category labeled "Sticky Properties" in block properties that would include a block picker and a checkbox, both of which would be blacked out if you didn't choose honey/slime block base.

The block picker would be labeled "Stick Blacklist". You could put any block(s) in the stick blacklist and that would allow the honey/slime blocks to NOT stick to any block(s) selected. This way we could use this to make certain blocks not stick to the honey/slime block.

The checkbox would be labeled "Stick to vanilla variants" which would allow whatever block base you chose to stick to its vanilla counterpart.

**Comment by Goldorion** [comment]
Check our changelog on the Discord
