### ISSUE TITLE
Get system time/date procedure blocks

### ISSUE THREAD

**Issue by MISMASJETU** [Team-MCToolkit/MCToolkit#71]
**Describe the feature**

A blocks for procedures which would get number of year, month, day, hour, minute, (maybe second) (seperated into multiple blocks)

**How would you implement it?**

I would put a blocks into math category or advanced or something like that. I know it's possible to make this since minecraft is already using it for halloween and christmas events (pumpkin monsters, christmas chests) and java supports it (I tryed it today in eclipse with some tutorial and it worked)
**Additional context**

This would open abillities to make limited time mod features, like gear you can only get through certain period of time.

**Comment by CrispyChips6660** [comment]
@Goldorion made a plugin for it, I'll try and merge it into MCToolkit core.
The plugin repo for reference: [https://github.com/ClothCreators/MCreatorPluginDate](https://github.com/ClothCreators/MCreatorPluginDate)

**Comment by Goldorion** [comment]
> @Goldorion made a plugin for it, I'll try and merge it into MCToolkit core.
> The plugin repo for reference: https://github.com/ClothCreators/MCreatorPluginDate

If your merge it, add the new variable type as a real variable (like the other ones, in local and global).

**Comment by MISMASJETU** [comment]
@CrispyChips6660  Nice. Thanks, I am not normally using plugins since I am afraid they could break my mod once I port it to another mc version or when new mcreator/mctoolkit build releases
