### ISSUE TITLE
Some features I need

### ISSUE THREAD

**Issue by TANC57** [Team-MCToolkit/MCToolkit#79]
At first the simplest.

New block

<[Get Player Nickname]

<[is entity in flight]

<[is entity moving]

<[Is entity aggressive]

For example a zombie that goes to hit a player will be considered aggressive and a zombie staying under the tree will not.

My next idea is new features for tamed animals.

Please add for them the ability to chase the owner in flight and the ability for players to fly on this animal, as well as a combination of movement on the ground and in the air. (Like on dragons from some modifications)

And the latter, in my opinion, is the most difficult. Changing mob models and textures using procedures.

New blocks:

Get provided entity model / texture.

[model / texture]

Change model / texture to [Optional]

Return the main model / texture

And so on...

If you do not understand something due to incorrect translation, ask me.

Please add these features. Many people are waiting for an update of my modification, and without them I will not be able to do it. Maybe some features have appeared in the new version. If so, ignore them.

**Comment by TANC57** [comment]
And one more question. Is it possible to import MCreator files into a new program and continue working on modifications?

**Comment by Max094Reikeb** [comment]
Few things to say :
1. I put this topic under "invalid" because you're definitely not respecting the "new feature request" template.
2. If you have multiple new feature requests, just create new posts.
3. Custom blocks/items/mob blockstates and models have already been requested, so there's no need to ask here.

**Comment by Max094Reikeb** [comment]
> And one more question. Is it possible to import MCreator files into a new program and continue working on modifications?

No, this isn't possible. MCToolkit will have some kind of converter so you can open your MCreator wokspace within it, but for the moment you can only open .mcreator files with MCreator.
