### ISSUE TITLE
Entity Tick Update

### ISSUE THREAD

**Issue by LoicMaitreDuFeu** [Team-MCToolkit/MCToolkit#84]
**Describe the feature**

A global trigger for Entity Tick Update will be very useful, like to detect if one entity in the world has a certain potion effect, Right now, it's only possible for custom entity triggers and can't be done to all entities in a global trigger

**Comment by Max094Reikeb** [comment]
I don't think it's possible because the listener (global trigger) would have to listen for all entities, it might be laggy, and not very useful for entities that are in un-loaded chuncks (if a player isn't in the chuncks to load the entity)

**Comment by LoicMaitreDuFeu** [comment]
Yeah but what suggestion do you have to achieve something like...
If an entity is burning in the world, it gives him a potion effect

**Comment by titedog** [comment]
Why don't you just make the trigger only tick for all mobs in the loaded chunk radius of a player? That way you could still achieve this and have less lag.

**Comment by LoicMaitreDuFeu** [comment]
might work aswell

**Comment by Max094Reikeb** [comment]
This won't definitely be added for performance issues.
