### ISSUE TITLE
Better Raycasting Procedures

### ISSUE THREAD

**Issue by titedog** [Team-MCToolkit/MCToolkit#88]
**DESCRIPTION:**

Better raycasting procedures would help a lot with raycasting for certain distances without having to duplicate many procedure blocks.

**IMPLEMENTATION:**

This feature would add 3 new procedure blocks for x y and z raycasting. These would raycasting until they reach a certain range of blocks. This would be very useful for raycasting if you wanted to say trace for a block in a range of 1-5 blocks in front of an entity. 

Blocks would look like this for example:

**Get block from [Event/Target Entity] x, raycasting distance [number input] to [number input]**

The above procedure block would be what it would look like for all of the raycasting blocks for x y and z. You could input 2 numbers and you could put a repeat to cycle through all blocks from the first input to the second one.

**Comment by Max094Reikeb** [comment]
Are you sure raytracing is in Minecraft Java?

**Comment by titedog** [comment]
I mean we already have raytracing procedures so I'm guessing yes?

**Comment by Max094Reikeb** [comment]
No we don't? Where?

**Comment by titedog** [comment]
[https://i.imgur.com/U2OWV74.png](url) Scroll almost all the way down in Entity Data.

**Comment by titedog** [comment]
https://i.imgur.com/U2OWV74.png nvm links are stupid so just copy and paste that

**Comment by CrispyChips6660** [comment]
I think you meant raycasting.

**Comment by titedog** [comment]
I meant raycasting my bad LOL

**Comment by Max094Reikeb** [comment]
Indeed this is not the same. Raytracing is a shader system that's close to real life sun & shadow.

**Comment by titedog** [comment]
Yes I know, I was just getting my words mixed up. I meant raycasting.

**Comment by Max094Reikeb** [comment]
Is this issue closed by this PR? [MCreator#716](https://github.com/MCreator/MCreator/pull/716)

**Comment by Max094Reikeb** [comment]
Closed via [MCreator#716](https://github.com/MCreator/MCreator/pull/716)
