### ISSUE TITLE
Destroy Block Drop

### ISSUE THREAD

**Issue by Trolmaso** [Team-MCToolkit/MCToolkit#89]
**Describe the feature**

Destroy Block Drop would be a procedure that destroys/removes the item(s) that drop from a block when it is broken

**How would you implement it?**

This feature would be added as a procedure block

**Additional context**

This feature would be useful for, for example, "realistic mods" that prevents the player from getting certain blocks/items without tools, or for enchantments that automatically smelt an ore when mined.

**Comment by Max094Reikeb** [comment]
You can already do it, just check if the player breaks a block, then check if player breaks it with the tool you want, and if not, cancel the event, replace the block at x y z with air, and damage the tool (or don't if the tool is the hand)

**Comment by Trolmaso** [comment]
Oh, sorry, I didn't realize that Cancel Event existed.
