### ISSUE TITLE
Many more in-app hints

### ISSUE THREAD

**Issue by MISMASJETU** [Team-MCToolkit/MCToolkit#9]
**Describe the feature**
Remember in-app hints from mcreator? I loved them, but there were a lot of them missing, could they be filled in or something?

**How would you implement it?**

Eh, add some text strings into the code or somethin'?

**Additional context**

Not at all. Thanks for your time

**Comment by Max094Reikeb** [comment]
Which in-app tips are missing? In which mod elements?

**Comment by Defeatomizer** [comment]
@Max094Reikeb MCreator#471 adds all missing help tips, just wait for when it is merged into MCreator:master and merge them into MCToolkit.
